server:
  port: 8100
spring:
  application:
    name: power
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.38.46:3306/power?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 521428Slyt!
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
  mail:
    host: smtp.qq.com
    username: 1178515826@qq.com
    password: uysnzvlpvavdbabc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 192.168.247.135
    port: 6379
    password: 521428Slyt
    database: 15
  data:
    redis:
      repositories:
        enabled: false
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
    #   开启发送确认
    publisher-confirms: true
    #   开启发送失败退回
    publisher-returns: true
    listener:
      direct:
        retry:
          enabled: true
        #       开启ACK
        acknowledge-mode: manual
      simple:
        retry:
          enabled: true
        acknowledge-mode: manual
        #       消费者的最小数量
        concurrency: 10
        #       消费者的最大数量
        max-concurrency: 20
        #       在单个请求中处理的消息个数，他应该大于等于事务数量
        prefetch: 5
        #       启动时自动启动容器
        auto-startup: true
        #       投递失败时是否重新排队
        default-requeue-rejected: true
    template:
      #     超时时间
      reply-timeout: 10000
      #     设置为true的时候RabbitTemplate(生产端)能够实现重试
      retry:
        enabled: true
        #       第一次与第二次发布消息的间隔
        initial-interval: 1000
        #       尝试发布消息的最大数量
        max-attempts: 3
        #       尝试发布消息的最大时间间隔
        max-interval: 10000
        #       上一次尝试时间间隔的乘数
        multiplier: 1.0
com:
  cdsen:
    admin:
      default-username: admin
      default-password: 19970621Sly
      default-email: 1178515826@qq.com
      avatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif
      introduction: 我是超级管理员
    admin-role:
      name: admin
      description: 超级管理员
      exclusive-permission: adminExclusive
      exclusive-permission-name: 超级管理员专属权限
    redisson:
      single:
        address: redis://192.168.247.135:6379
        password: 521428Slyt
        database: 14
dubbo:
  application:
    name: power-admin
  registry:
    address: zookeeper://118.24.38.46:2181
app:
  id: Power
apollo:
  meta: http://127.0.0.1:8080

